import type { AliasToken } from "antd/es/theme/interface";

export const lightColorTheme: Partial<AliasToken> = {
	colorPrimary: "#7C3AED",
	colorInfo: "#8B5CF6",
	colorSuccess: "#10B981",
	colorWarning: "#F59E0B",
	colorError: "#EF4444",
	colorTextBase: "#1E1E1E",
	colorTextSecondary: "#4B5563",
	colorTextTertiary: "rgba(0,0,0,0.45)",
	colorTextQuaternary: "rgba(0,0,0,0.25)",
	colorTextPlaceholder: "rgba(0,0,0,0.45)",
	colorLink: "#7C3AED",
	colorLinkHover: "#8B5CF6",
	colorLinkActive: "#6D28D9",
	colorBgBase: "#FFFFFF",
	colorBgContainer: "#FAFAFA",
	colorBgLayout: "#FFFFFF",
	colorFill: "#F9FAFB",
	colorFillSecondary: "#F4F3FF",
	colorBorder: "#E5E7EB",
	colorBorderSecondary: "#D1D5DB",
	fontFamily: "Inter, 'Segoe UI', Roboto, sans-serif",
	fontSize: 14,
	lineHeight: 1.5,
	borderRadius: 8,
	borderRadiusSM: 4,
	sizeStep: 4,
	controlHeight: 32,
	controlHeightLG: 40,
	controlHeightSM: 24,
	motionDurationSlow: "0.3",
	motionDurationMid: "0.15",
	motionDurationFast: "0.1",
	colorBgContainerDisabled: "rgba(0,0,0,0.25)",
	wireframe: false,
};
